#!/bin/sh

# PROVIDE: xe_daemon
# REQUIRE: login
# KEYWORD: nojail shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# xe_daemon_enable (bool): Set to NO by default.
#       Set it to YES to enable xe_daemon.
#

. /etc/rc.subr

name=xe_daemon
rcvar=xe_daemon_enable

command=/usr/local/sbin/xe_wrapper
command_interpreter="/bin/sh -T"
command_args="/usr/local/sbin/xe-daemon &"
start_precmd="xe_daemon_startprecmd"

load_rc_config $name

pidfile="/var/run/xe_wrapper.pid"
: ${xe_daemon_enable="NO"}

xe_daemon_startprecmd()
{
# seed the xe-linux-distribution cache file for Xen
cat > /var/cache/xe-linux-distribution <<FOO
os_distro="`uname -s`"
os_majorver=""
os_minorver=""
os_uname="`uname -r`"
os_name="`uname -s` `uname -r`"
FOO
}

run_rc_command "$1"
