#!/bin/sh

# PROVIDE: xe_daemon
# REQUIRE: login
# KEYWORD: nojail shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# xe_daemon_enable (bool): Set to NO by default.
#       Set it to YES to enable xe_daemon.
#

. /etc/rc.subr

name="xe_daemon"
rcvar=`set_rcvar`

xe_daemon_enable=${xe_daemon_enable:-"NO"}
pidfile=/var/run/${name}.pid

command=/usr/local/sbin/xe-daemon
command_args="-p ${pidfile}"
start_precmd="xe_daemon_startprecmd"

xe_daemon_startprecmd()
{
# seed the xe-linux-distribution cache file for Xen
cat > /var/cache/xe-linux-distribution <<FOO
os_distro="`uname -s`"
os_majorver=""
os_minorver=""
os_uname="`uname -r`"
os_name="`uname -s` `uname -r`"
FOO
}

run_rc_command "$1"
